name: apr 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  apr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Calculate APR
        run: |
          pip install -r requirements.txt 
          python apr.py
      - name: Commit report
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@noreply.github.com'
          git commit -am "Update data"
          git push