name: xtri 
on:
  workflow_dispatch:

jobs:
  xtri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Convert fees and calculate APR
        run: |
          pip install -r requirements.txt 
          python xtri.py
      - name: Commit report
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@noreply.github.com'
          git commit -am "Update xTRI"
          git push
